### ISSUE TITLE
Cannot connect to jira

### ISSUE THREAD

**Issue by pawelmilka** [KnisterPeter/vscode-jira#24] opened 2017-11-23 14:16 UTC
After extension update to version 0.5.1 I cannot connect to Jira anymore.
Output log:
Failed to contact JIRA server using 'https://jira.mydomain.com/jira/'. Please check url and credentials
Headers is not defined

**Comment by KnisterPeter** [comment] 2017-11-25 08:18
Oh, this looks like a regression. I'll fix that.

**Comment by KnisterPeter** [comment] 2017-11-25 08:24
Fix released as 0.5.2

**Closed as completed** 2017-11-25 08:23 UTC
Labels: bug
